-- Create the game_plays table
CREATE TABLE public.game_plays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID DEFAULT auth.uid() NOT NULL,
    reward_id UUID,
    win BOOLEAN NOT NULL,
    CONSTRAINT game_plays_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT game_plays_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES public.prizes(id) ON DELETE SET NULL
);

-- Add comments to the table and columns
COMMENT ON TABLE public.game_plays IS 'Stores records of games played by users.';
COMMENT ON COLUMN public.game_plays.id IS 'Unique identifier for each game play record.';
COMMENT ON COLUMN public.game_plays.created_at IS 'Timestamp of when the game was played.';
COMMENT ON COLUMN public.game_plays.user_id IS 'Foreign key to the user who played the game.';
COMMENT ON COLUMN public.game_plays.reward_id IS 'Foreign key to the prize associated with the game.';
COMMENT ON COLUMN public.game_plays.win IS 'Indicates whether the user won the game (true) or lost (false).';


-- Enable Row Level Security
ALTER TABLE public.game_plays ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Allow users to insert their own game_plays"
ON public.game_plays
FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to select their own game_plays"
ON public.game_plays
FOR SELECT
USING (auth.uid() = user_id); 